### ISSUE TITLE
Terraform 0.13 support

### ISSUE THREAD

**Issue by kuzmacska** [datadrivers/terraform-provider-nexus#80] opened 2020-08-24 14:29 UTC
Could you guys add support for Terraform 0.13?
Now it is mandatory to upload binary like in the guide below:
https://www.terraform.io/upgrade-guides/0-13.html#in-house-providers

**Comment by Skaronator** [comment] 2020-08-25 06:15
Duplicate of #76 which has been closed even though it isn't done.

**Comment by anmoel** [comment] 2020-12-04 13:21
Hi,

now we have added our provider to the terraform registry.
see https://registry.terraform.io/providers/datadrivers/nexus/latest

kind regards

André

**Closed by anmoel** 2020-12-04 13:21 UTC
